name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sanjacob/country-iso@master
        id: country
        with:
          name: Mexico
      - name: Check the outputs
        run: |
          echo "${{ steps.country.outputs.iso-2 }}"
          echo "${{ steps.country.outputs.iso-3 }}"
          echo "${{ steps.country.outputs.name }}"
          echo "${{ steps.country.outputs.native }}"
          echo "${{ steps.country.outputs.continent }}"
      - name: Check if iso-2 is correct
        if: ${{ steps.country.outputs.iso-2 != 'MX' }}
        run: exit 1
      - name: Check if iso-3 is correct
        if: ${{ steps.country.outputs.iso-3 != 'MEX' }}
        run: exit 1
      - name: Check if continent is correct
        if: ${{ steps.country.outputs.continent != 'NA' }}
        run: exit 1
